default_platform(:ios)

platform :ios do

  desc "Wraply iOS release build"

  lane :release do |options|

    require 'spaceship'

    scheme = options[:scheme] || ENV["SCHEME"] || "template"
    output_dir = options[:output_dir] || "build"
    app_id = ENV["BUNDLE_IDENTIFIER"]
    identity = ENV["CODE_SIGN_IDENTITY"] || "Apple Distribution"

    # -------------------------------------------------
    # Apple API Key
    # -------------------------------------------------

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"]
    )

    Spaceship::ConnectAPI.token = Spaceship::ConnectAPI::Token.create(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      filepath: ENV["ASC_KEY_PATH"]
    )

    # -------------------------------------------------
    # 🔍 Apple cert 조회
    # -------------------------------------------------

    UI.message("🔍 Checking Apple certificates...")

    certs = Spaceship::ConnectAPI::Certificate.all(
      filter: { certificateType: "DISTRIBUTION" }
    )

    apple_cert_exists = certs.any?

    puts "WRAPLY_APPLE_CERT_EXISTS=#{apple_cert_exists}"

    if apple_cert_exists
      UI.success("✅ Apple cert exists")
    else
      UI.important("❌ No Apple cert found")
    end

    # -------------------------------------------------
    # 🔐 cert 처리
    # -------------------------------------------------

    if ENV["HAS_CERT"] == "true"

      UI.message("🔐 Using cached certificate")

      import_certificate(
        certificate_path: ENV["P12_PATH"],
        certificate_password: ENV["P12_PASSWORD"],
        keychain_path: ENV["FASTLANE_KEYCHAIN_PATH"],
        keychain_password: ENV["FASTLANE_KEYCHAIN_PASSWORD"]
        log_output: true
      )

      begin
        sh("security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV['FASTLANE_KEYCHAIN_PASSWORD']} #{ENV['FASTLANE_KEYCHAIN_PATH']}")
      rescue
        UI.message("⚠️ key partition skip")
      end

    else

      if apple_cert_exists

        UI.important("⚠️ Apple cert exists but no local p12 → skip creation")

      else

        begin

          UI.message("⚡ Creating new cert")

          cert(
            api_key: api_key,
            development: false,
            force: false,
            generate_apple_certs: false,
            keychain_path: ENV["FASTLANE_KEYCHAIN_PATH"],
            keychain_password: ENV["FASTLANE_KEYCHAIN_PASSWORD"]
          )

          puts "WRAPLY_CERT_CREATED=true"

        rescue => e

          UI.important("⚠️ cert creation failed")
          puts "WRAPLY_CERT_CREATED=false"
          puts "CERT_ERROR=#{e.message}"

        end

      end

    end

    # -------------------------------------------------
    # provisioning
    # -------------------------------------------------

    if ENV["HAS_PROFILE"] == "true"

      UI.message("📄 Using cached provisioning profile")

      ENV["SIGH_PROFILE_PATH"] = ENV["PROFILE_PATH"]

    else

      UI.message("📄 Creating provisioning profile")

      sigh(
        api_key: api_key,
        app_identifier: app_id,
        skip_certificate_verification: true,
        # skip_fetch_profiles: false,
        # force: false
        force: true
      )

      profile_path = Actions.lane_context[
        SharedValues::SIGH_PROFILE_PATH
      ]
      profile_uuid = File.basename(profile_path, ".mobileprovision")

      puts "WRAPLY_PROFILE_PATH=#{profile_path}"
      puts "WRAPLY_PROFILE_UUID=#{profile_uuid}"

    end

    UI.message("📄 PROFILE: #{ENV['SIGH_NAME']}")
    UI.message("🆔 TEAM: #{ENV['TEAM_ID']}")

    # -------------------------------------------------
    # signing 설정
    # -------------------------------------------------

    update_project_provisioning(
      xcodeproj: "template.xcodeproj",
      profile: ENV["SIGH_PROFILE_PATH"],
      code_signing_identity: identity
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "template.xcodeproj",
      targets: ["template"],
      build_configurations: ["Release"],
      team_id: ENV["TEAM_ID"],
      code_sign_identity: identity
    )

    # -------------------------------------------------
    # build
    # -------------------------------------------------

    build_ios_app(
      scheme: scheme,
      configuration: "Release",
      clean: true,
      export_method: "app-store",

      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          app_id => ENV["SIGH_NAME"]
        }
      },

      xcargs: [
        "CODE_SIGN_STYLE=Manual",
        "DEVELOPMENT_TEAM=#{ENV['TEAM_ID']}",
        "CODE_SIGN_IDENTITY=\"#{identity}\""
      ].join(" "),

      output_directory: output_dir,
      output_name: "app.ipa"
    )

  end

end